on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec_file:
         - "01.cy.js"
         - "02.cy.js"
         - "03.cy.js"
         - "04.cy.js"
         - "05.cy.js"
         - "06.cy.js"
         - "07.cy.js"
         - "08.cy.js"
         - "09.cy.js"
         - "10.cy.js"
         - "11.cy.js"
         - "12.cy.js"
         - "13.cy.js"
         - "14.cy.js"
         - "15.cy.js"
         - "16.cy.js"
         - "17.cy.js"
         - "20.cy.js"
         - "21.cy.js"
         - "20.cy.js"
         - "21.cy.js"
         - "22.cy.js"
         - "23.cy.js"
         - "24.cy.js"
         - "25.cy.js"
         - "26.cy.js"
         - "27.cy.js"
         - "28.cy.js"
         - "29.cy.js"
         - "30.cy.js"
         - "31.cy.js"
         - "32.cy.js"
         - "33.cy.js"
         - "34.cy.js"
         - "35.cy.js"
         - "36.cy.js"
         - "37.cy.js"
         - "38.cy.js"
         - "39.cy.js"
         - "40.cy.js"
         - "41.cy.js"
         - "42.cy.js"
         - "43.cy.js"
         - "44.cy.js"
         - "45.cy.js"
         - "46.cy.js"
         - "47.cy.js"
         - "48.cy.js"
         - "49.cy.js"
         - "50.cy.js"
         - "51.cy.js"
         - "52.cy.js"
         - "53.cy.js"
         - "54.cy.js"
         - "55.cy.js"
         - "56.cy.js"
         - "57.cy.js"
         - "58.cy.js"
         - "59.cy.js"
         - "60.cy.js"
         - "61.cy.js"
         - "62.cy.js"
         - "63.cy.js"
         - "64.cy.js"
         - "65.cy.js"
         - "66.cy.js"
         - "67.cy.js"
         - "68.cy.js"
         - "69.cy.js"
         - "70.cy.js"
         - "71.cy.js"
         - "72.cy.js"
         - "73.cy.js"
         - "74.cy.js"
             
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          # Add any additional setup steps here, if needed

      - name: Run Cypress tests
        run: |
          npx cypress install # This ensures Cypress is installed and up-to-date
          # Wrap the Cypress run command in a try-catch block
          set +e
          npx cypress run --spec "cypress/e2e/${{ matrix.spec_file }}" --config video=false --record --key fede15fc-970a-4cb4-a077-518573466e27
          # Store the exit code in a variable
          EXIT_CODE=$?
          # Set back to normal behavior (exit on error)
          set -e
          # Check if the exit code is non-zero (indicating failure)
          if [ $EXIT_CODE -ne 0 ]; then
            echo "Some tests failed but continuing..."
          fi

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: 390 - 410 k
          path: |
            cypress/videos
            cypress/screenshots
            cypress/fixtures/missing_elements3003.json
            cypress/fixtures/missing_elements3004.json
            cypress/fixtures/missing_elements3005.json
            cypress/fixtures/missing_elements3006.json
            cypress/fixtures/missing_elements3007.json
            cypress/fixtures/missing_elements3008.json
            cypress/fixtures/missing_elements3009.json
            cypress/fixtures/missing_elements3010.json
            cypress/fixtures/missing_elements3011.json
            cypress/fixtures/missing_elements3012.json
            cypress/fixtures/missing_elements3013.json
            cypress/fixtures/missing_elements3014.json
            cypress/fixtures/missing_elements3015.json
            cypress/fixtures/missing_elements3016.json
            cypress/fixtures/missing_elements3017.json
            cypress/fixtures/missing_elements3018.json
            cypress/fixtures/missing_elements3019.json
            cypress/fixtures/missing_elements3020.json
            cypress/fixtures/missing_elements3021.json
            cypress/fixtures/missing_elements3022.json
            cypress/fixtures/missing_elements3023.json
            cypress/fixtures/missing_elements3024.json
            cypress/fixtures/missing_elements3025.json
            cypress/fixtures/missing_elements3026.json
            cypress/fixtures/missing_elements3027.json
            cypress/fixtures/missing_elements3028.json
            cypress/fixtures/missing_elements3029.json
            cypress/fixtures/missing_elements3030.json
            cypress/fixtures/missing_elements3031.json
            cypress/fixtures/missing_elements3032.json
            cypress/fixtures/missing_elements3033.json
            cypress/fixtures/missing_elements3034.json
            cypress/fixtures/missing_elements3035.json
            cypress/fixtures/missing_elements3036.json
            cypress/fixtures/missing_elements3037.json
            cypress/fixtures/missing_elements3038.json
            cypress/fixtures/missing_elements3039.json
            cypress/fixtures/missing_elements3040.json
            cypress/fixtures/missing_elements3041.json
            cypress/fixtures/missing_elements3042.json
            cypress/fixtures/missing_elements3043.json
            cypress/fixtures/missing_elements3044.json
            cypress/fixtures/missing_elements3045.json
            cypress/fixtures/missing_elements3046.json
            cypress/fixtures/missing_elements3047.json
            cypress/fixtures/missing_elements3048.json
            cypress/fixtures/missing_elements3049.json
            cypress/fixtures/missing_elements3050.json
            cypress/fixtures/missing_elements3051.json
            cypress/fixtures/missing_elements3052.json
            cypress/fixtures/missing_elements3053.json
            cypress/fixtures/missing_elements3054.json
            cypress/fixtures/missing_elements3055.json
            cypress/fixtures/missing_elements3056.json
            cypress/fixtures/missing_elements3057.json
            cypress/fixtures/missing_elements3058.json
            cypress/fixtures/missing_elements3059.json
            cypress/fixtures/missing_elements3060.json
            cypress/fixtures/missing_elements3061.json
            cypress/fixtures/missing_elements3062.json
            cypress/fixtures/missing_elements3063.json
            cypress/fixtures/missing_elements3064.json
            cypress/fixtures/missing_elements3065.json
            cypress/fixtures/missing_elements3066.json
            cypress/fixtures/missing_elements3067.json
            cypress/fixtures/missing_elements3068.json
            cypress/fixtures/missing_elements3069.json
            cypress/fixtures/missing_elements3070.json
            cypress/fixtures/missing_elements3071.json
            cypress/fixtures/missing_elements3072.json
            cypress/fixtures/missing_elements3073.json
            cypress/fixtures/missing_elements3074.json
            cypress/fixtures/missing_elements3075.json
            cypress/fixtures/missing_elements3076.json
            cypress/fixtures/missing_elements3077.json
            cypress/fixtures/missing_elements3078.json
            cypress/fixtures/missing_elements3079.json
            cypress/fixtures/missing_elements3080.json
            cypress/fixtures/missing_elements3081.json
            cypress/fixtures/missing_elements3082.json
            cypress/fixtures/missing_elements3083.json
            cypress/fixtures/missing_elements3084.json
            cypress/fixtures/missing_elements3085.json
            cypress/fixtures/missing_elements3086.json
            cypress/fixtures/missing_elements3087.json
            cypress/fixtures/missing_elements3088.json
            cypress/fixtures/missing_elements3089.json
            cypress/fixtures/missing_elements3090.json
            cypress/fixtures/missing_elements3091.json
            cypress/fixtures/missing_elements3092.json
            cypress/fixtures/missing_elements3093.json
            cypress/fixtures/missing_elements3094.json
            cypress/fixtures/missing_elements3095.json
            cypress/fixtures/missing_elements3096.json
            cypress/fixtures/missing_elements3097.json
            cypress/fixtures/missing_elements3098.json
            cypress/fixtures/missing_elements3099.json
            cypress/fixtures/missing_elements3100.json
            cypress/fixtures/missing_elements3101.json
            cypress/fixtures/missing_elements3102.json
            cypress/fixtures/missing_elements3103.json
            cypress/fixtures/missing_elements3104.json
            cypress/fixtures/missing_elements3105.json
            cypress/fixtures/missing_elements3106.json
            cypress/fixtures/missing_elements3107.json
            cypress/fixtures/missing_elements3108.json
            cypress/fixtures/missing_elements3109.json
            cypress/fixtures/missing_elements3110.json
            cypress/fixtures/missing_elements3111.json
            cypress/fixtures/missing_elements3112.json
            cypress/fixtures/missing_elements3113.json
            cypress/fixtures/missing_elements3114.json
            cypress/fixtures/missing_elements3115.json
            cypress/fixtures/missing_elements3116.json
            cypress/fixtures/missing_elements3117.json
            cypress/fixtures/missing_elements3118.json
            cypress/fixtures/missing_elements3119.json
            cypress/fixtures/missing_elements3120.json
            cypress/fixtures/missing_elements3121.json
            cypress/fixtures/missing_elements3122.json
            cypress/fixtures/missing_elements3123.json
            cypress/fixtures/missing_elements3124.json
            cypress/fixtures/missing_elements3125.json
            cypress/fixtures/missing_elements3126.json
            cypress/fixtures/missing_elements3127.json
            cypress/fixtures/missing_elements3128.json
            cypress/fixtures/missing_elements3129.json
            cypress/fixtures/missing_elements3130.json
            cypress/fixtures/missing_elements3131.json
            cypress/fixtures/missing_elements3132.json
            cypress/fixtures/missing_elements3133.json
            cypress/fixtures/missing_elements3134.json
            cypress/fixtures/missing_elements3135.json
            cypress/fixtures/missing_elements3136.json
            cypress/fixtures/missing_elements3137.json
            cypress/fixtures/missing_elements3138.json
            cypress/fixtures/missing_elements3139.json
            cypress/fixtures/missing_elements3140.json
            cypress/fixtures/missing_elements3141.json
            cypress/fixtures/missing_elements3142.json
            cypress/fixtures/missing_elements3143.json
            cypress/fixtures/missing_elements3144.json
            cypress/fixtures/missing_elements3145.json
            cypress/fixtures/missing_elements3146.json
            cypress/fixtures/missing_elements3147.json
            cypress/fixtures/missing_elements3148.json
            cypress/fixtures/missing_elements3149.json
            cypress/fixtures/missing_elements3150.json
            cypress/fixtures/missing_elements3151.json
            cypress/fixtures/missing_elements3152.json
            cypress/fixtures/missing_elements3153.json
            cypress/fixtures/missing_elements3154.json
            cypress/fixtures/missing_elements3155.json
            cypress/fixtures/missing_elements3156.json
            cypress/fixtures/missing_elements3157.json
            cypress/fixtures/missing_elements3158.json
            cypress/fixtures/missing_elements3159.json
            cypress/fixtures/missing_elements3160.json
            cypress/fixtures/missing_elements3161.json
            cypress/fixtures/missing_elements3162.json
            cypress/fixtures/missing_elements3163.json
            cypress/fixtures/missing_elements3164.json
            cypress/fixtures/missing_elements3165.json
            cypress/fixtures/missing_elements3166.json
            cypress/fixtures/missing_elements3167.json
            cypress/fixtures/missing_elements3168.json
            cypress/fixtures/missing_elements3169.json
            cypress/fixtures/missing_elements3170.json
            cypress/fixtures/missing_elements3171.json
            cypress/fixtures/missing_elements3172.json
            cypress/fixtures/missing_elements3173.json
            cypress/fixtures/missing_elements3174.json
            cypress/fixtures/missing_elements3175.json
            cypress/fixtures/missing_elements3176.json
            cypress/fixtures/missing_elements3177.json
            cypress/fixtures/missing_elements3178.json
            cypress/fixtures/missing_elements3179.json
            cypress/fixtures/missing_elements3180.json
            cypress/fixtures/missing_elements3181.json
            cypress/fixtures/missing_elements3182.json
            cypress/fixtures/missing_elements3183.json
            cypress/fixtures/missing_elements3184.json
            cypress/fixtures/missing_elements3185.json
            cypress/fixtures/missing_elements3186.json
            cypress/fixtures/missing_elements3187.json
            cypress/fixtures/missing_elements3188.json
            cypress/fixtures/missing_elements3189.json
            cypress/fixtures/missing_elements3190.json
            cypress/fixtures/missing_elements3191.json
            cypress/fixtures/missing_elements3192.json
            cypress/fixtures/missing_elements3193.json
            cypress/fixtures/missing_elements3194.json
            cypress/fixtures/missing_elements3195.json
            cypress/fixtures/missing_elements3196.json
            cypress/fixtures/missing_elements3197.json
            cypress/fixtures/missing_elements3198.json
            cypress/fixtures/missing_elements3199.json
            cypress/fixtures/missing_elements3200.json
            cypress/fixtures/missing_elements3201.json
            cypress/fixtures/missing_elements3202.json
