on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec_file:
         - "01.cy.js"
         - "02.cy.js"
         - "03.cy.js"
         - "04.cy.js"
         - "05.cy.js"
         - "06.cy.js"
         - "07.cy.js"
         - "08.cy.js"
         - "09.cy.js"
         - "10.cy.js"
         - "11.cy.js"
         - "12.cy.js"
         - "13.cy.js"
         - "14.cy.js"
         - "15.cy.js"
         - "16.cy.js"
         - "17.cy.js"
         - "20.cy.js"
         - "21.cy.js"
         - "20.cy.js"
         - "21.cy.js"
         - "22.cy.js"
         - "23.cy.js"
         - "24.cy.js"
         - "25.cy.js"
         - "26.cy.js"
         - "27.cy.js"
         - "28.cy.js"
         - "29.cy.js"
         - "30.cy.js"
         - "31.cy.js"
         - "32.cy.js"
         - "33.cy.js"
         - "34.cy.js"
         - "35.cy.js"
         - "36.cy.js"
         - "37.cy.js"
         - "38.cy.js"
         - "39.cy.js"
         - "40.cy.js"
         - "41.cy.js"
         - "42.cy.js"
         - "43.cy.js"
         - "44.cy.js"
         - "45.cy.js"
         - "46.cy.js"
         - "47.cy.js"
         - "48.cy.js"
         - "49.cy.js"
         - "50.cy.js"
         - "51.cy.js"
         - "52.cy.js"
         - "53.cy.js"
         - "54.cy.js"
         - "55.cy.js"
         - "56.cy.js"
         - "57.cy.js"
         - "58.cy.js"
         - "59.cy.js"
         - "60.cy.js"
         - "61.cy.js"
         - "62.cy.js"
         - "63.cy.js"
         - "64.cy.js"
         - "65.cy.js"
         - "66.cy.js"
         - "67.cy.js"
         - "68.cy.js"
         - "69.cy.js"
         - "70.cy.js"
         - "71.cy.js"
         - "72.cy.js"
         - "73.cy.js"
         - "74.cy.js"
         - "75.cy.js"
         - "76.cy.js"
         - "77.cy.js"
         - "78.cy.js"
         - "79.cy.js"
         - "80.cy.js"
         - "81.cy.js"
         - "82.cy.js"
         - "83.cy.js"
         - "84.cy.js"
         - "85.cy.js"
         - "86.cy.js"
         - "87.cy.js"
         - "88.cy.js"
         - "89.cy.js"
         - "90.cy.js"
         - "91.cy.js"
         - "92.cy.js"
         - "93.cy.js"
         - "94.cy.js"
         - "95.cy.js"
         - "96.cy.js"
         - "97.cy.js"
         - "98.cy.js"
         - "99.cy.js"
         - "100.cy.js"


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run --spec "cypress/e2e/${{ matrix.spec_file }}" --config video=false --record --key fede15fc-970a-4cb4-a077-518573466e27

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
            cypress/fixtures/missing_elements2403.json
              cypress/fixtures/missing_elements2404.json
              cypress/fixtures/missing_elements2405.json
              cypress/fixtures/missing_elements2406.json
              cypress/fixtures/missing_elements2407.json
              cypress/fixtures/missing_elements2408.json
              cypress/fixtures/missing_elements2409.json
              cypress/fixtures/missing_elements2410.json
              cypress/fixtures/missing_elements2411.json
              cypress/fixtures/missing_elements2412.json
              cypress/fixtures/missing_elements2413.json
              cypress/fixtures/missing_elements2414.json
              cypress/fixtures/missing_elements2415.json
              cypress/fixtures/missing_elements2416.json
              cypress/fixtures/missing_elements2417.json
              cypress/fixtures/missing_elements2418.json
              cypress/fixtures/missing_elements2419.json
              cypress/fixtures/missing_elements2420.json
              cypress/fixtures/missing_elements2421.json
              cypress/fixtures/missing_elements2422.json
              cypress/fixtures/missing_elements2423.json
              cypress/fixtures/missing_elements2424.json
              cypress/fixtures/missing_elements2425.json
              cypress/fixtures/missing_elements2426.json
              cypress/fixtures/missing_elements2427.json
              cypress/fixtures/missing_elements2428.json
              cypress/fixtures/missing_elements2429.json
              cypress/fixtures/missing_elements2430.json
              cypress/fixtures/missing_elements2431.json
              cypress/fixtures/missing_elements2432.json
              cypress/fixtures/missing_elements2433.json
              cypress/fixtures/missing_elements2434.json
              cypress/fixtures/missing_elements2435.json
              cypress/fixtures/missing_elements2436.json
              cypress/fixtures/missing_elements2437.json
              cypress/fixtures/missing_elements2438.json
              cypress/fixtures/missing_elements2439.json
              cypress/fixtures/missing_elements2440.json
              cypress/fixtures/missing_elements2441.json
              cypress/fixtures/missing_elements2442.json
              cypress/fixtures/missing_elements2443.json
              cypress/fixtures/missing_elements2444.json
              cypress/fixtures/missing_elements2445.json
              cypress/fixtures/missing_elements2446.json
              cypress/fixtures/missing_elements2447.json
              cypress/fixtures/missing_elements2448.json
              cypress/fixtures/missing_elements2449.json
              cypress/fixtures/missing_elements2450.json
              cypress/fixtures/missing_elements2451.json
              cypress/fixtures/missing_elements2452.json
              cypress/fixtures/missing_elements2453.json
              cypress/fixtures/missing_elements2454.json
              cypress/fixtures/missing_elements2455.json
              cypress/fixtures/missing_elements2456.json
              cypress/fixtures/missing_elements2457.json
              cypress/fixtures/missing_elements2458.json
              cypress/fixtures/missing_elements2459.json
              cypress/fixtures/missing_elements2460.json
              cypress/fixtures/missing_elements2461.json
              cypress/fixtures/missing_elements2462.json
              cypress/fixtures/missing_elements2463.json
              cypress/fixtures/missing_elements2464.json
              cypress/fixtures/missing_elements2465.json
              cypress/fixtures/missing_elements2466.json
              cypress/fixtures/missing_elements2467.json
              cypress/fixtures/missing_elements2468.json
              cypress/fixtures/missing_elements2469.json
              cypress/fixtures/missing_elements2470.json
              cypress/fixtures/missing_elements2471.json
              cypress/fixtures/missing_elements2472.json
              cypress/fixtures/missing_elements2473.json
              cypress/fixtures/missing_elements2474.json
              cypress/fixtures/missing_elements2475.json
              cypress/fixtures/missing_elements2476.json
              cypress/fixtures/missing_elements2477.json
              cypress/fixtures/missing_elements2478.json
              cypress/fixtures/missing_elements2479.json
              cypress/fixtures/missing_elements2480.json
              cypress/fixtures/missing_elements2481.json
              cypress/fixtures/missing_elements2482.json
              cypress/fixtures/missing_elements2483.json
              cypress/fixtures/missing_elements2484.json
              cypress/fixtures/missing_elements2485.json
              cypress/fixtures/missing_elements2486.json
              cypress/fixtures/missing_elements2487.json
              cypress/fixtures/missing_elements2488.json
              cypress/fixtures/missing_elements2489.json
              cypress/fixtures/missing_elements2490.json
              cypress/fixtures/missing_elements2491.json
              cypress/fixtures/missing_elements2492.json
              cypress/fixtures/missing_elements2493.json
              cypress/fixtures/missing_elements2494.json
              cypress/fixtures/missing_elements2495.json
              cypress/fixtures/missing_elements2496.json
              cypress/fixtures/missing_elements2497.json
              cypress/fixtures/missing_elements2498.json
              cypress/fixtures/missing_elements2499.json
              cypress/fixtures/missing_elements2500.json
              cypress/fixtures/missing_elements2501.json
              cypress/fixtures/missing_elements2502.json
              cypress/fixtures/missing_elements2503.json
              cypress/fixtures/missing_elements2504.json
              cypress/fixtures/missing_elements2505.json
              cypress/fixtures/missing_elements2506.json
              cypress/fixtures/missing_elements2507.json
              cypress/fixtures/missing_elements2508.json
              cypress/fixtures/missing_elements2509.json
              cypress/fixtures/missing_elements2510.json
              cypress/fixtures/missing_elements2511.json
              cypress/fixtures/missing_elements2512.json
              cypress/fixtures/missing_elements2513.json
              cypress/fixtures/missing_elements2514.json
              cypress/fixtures/missing_elements2515.json
              cypress/fixtures/missing_elements2516.json
              cypress/fixtures/missing_elements2517.json
              cypress/fixtures/missing_elements2518.json
              cypress/fixtures/missing_elements2519.json
              cypress/fixtures/missing_elements2520.json
              cypress/fixtures/missing_elements2521.json
              cypress/fixtures/missing_elements2522.json
              cypress/fixtures/missing_elements2523.json
              cypress/fixtures/missing_elements2524.json
              cypress/fixtures/missing_elements2525.json
              cypress/fixtures/missing_elements2526.json
              cypress/fixtures/missing_elements2527.json
              cypress/fixtures/missing_elements2528.json
              cypress/fixtures/missing_elements2529.json
              cypress/fixtures/missing_elements2530.json
              cypress/fixtures/missing_elements2531.json
              cypress/fixtures/missing_elements2532.json
              cypress/fixtures/missing_elements2533.json
              cypress/fixtures/missing_elements2534.json
              cypress/fixtures/missing_elements2535.json
              cypress/fixtures/missing_elements2536.json
              cypress/fixtures/missing_elements2537.json
              cypress/fixtures/missing_elements2538.json
              cypress/fixtures/missing_elements2539.json
              cypress/fixtures/missing_elements2540.json
              cypress/fixtures/missing_elements2541.json
              cypress/fixtures/missing_elements2542.json
              cypress/fixtures/missing_elements2543.json
              cypress/fixtures/missing_elements2544.json
              cypress/fixtures/missing_elements2545.json
              cypress/fixtures/missing_elements2546.json
              cypress/fixtures/missing_elements2547.json
              cypress/fixtures/missing_elements2548.json
              cypress/fixtures/missing_elements2549.json
              cypress/fixtures/missing_elements2550.json
              cypress/fixtures/missing_elements2551.json
              cypress/fixtures/missing_elements2552.json
              cypress/fixtures/missing_elements2553.json
              cypress/fixtures/missing_elements2554.json
              cypress/fixtures/missing_elements2555.json
              cypress/fixtures/missing_elements2556.json
              cypress/fixtures/missing_elements2557.json
              cypress/fixtures/missing_elements2558.json
              cypress/fixtures/missing_elements2559.json
              cypress/fixtures/missing_elements2560.json
              cypress/fixtures/missing_elements2561.json
              cypress/fixtures/missing_elements2562.json
              cypress/fixtures/missing_elements2563.json
              cypress/fixtures/missing_elements2564.json
              cypress/fixtures/missing_elements2565.json
              cypress/fixtures/missing_elements2566.json
              cypress/fixtures/missing_elements2567.json
              cypress/fixtures/missing_elements2568.json
              cypress/fixtures/missing_elements2569.json
              cypress/fixtures/missing_elements2570.json
              cypress/fixtures/missing_elements2571.json
              cypress/fixtures/missing_elements2572.json
              cypress/fixtures/missing_elements2573.json
              cypress/fixtures/missing_elements2574.json
              cypress/fixtures/missing_elements2575.json
              cypress/fixtures/missing_elements2576.json
              cypress/fixtures/missing_elements2577.json
              cypress/fixtures/missing_elements2578.json
              cypress/fixtures/missing_elements2579.json
              cypress/fixtures/missing_elements2580.json
              cypress/fixtures/missing_elements2581.json
              cypress/fixtures/missing_elements2582.json
              cypress/fixtures/missing_elements2583.json
              cypress/fixtures/missing_elements2584.json
              cypress/fixtures/missing_elements2585.json
              cypress/fixtures/missing_elements2586.json
              cypress/fixtures/missing_elements2587.json
              cypress/fixtures/missing_elements2588.json
              cypress/fixtures/missing_elements2589.json
              cypress/fixtures/missing_elements2590.json
              cypress/fixtures/missing_elements2591.json
              cypress/fixtures/missing_elements2592.json
              cypress/fixtures/missing_elements2593.json
              cypress/fixtures/missing_elements2594.json
              cypress/fixtures/missing_elements2595.json
              cypress/fixtures/missing_elements2596.json
              cypress/fixtures/missing_elements2597.json
              cypress/fixtures/missing_elements2598.json
              cypress/fixtures/missing_elements2599.json
              cypress/fixtures/missing_elements2600.json
              cypress/fixtures/missing_elements2601.json
              cypress/fixtures/missing_elements2602.json



