on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec_file:
         - "01.cy.js"
         - "02.cy.js"
         - "03.cy.js"
         - "04.cy.js"
         - "05.cy.js"
         - "06.cy.js"
         - "07.cy.js"
         - "08.cy.js"
         - "09.cy.js"
         - "10.cy.js"
         - "11.cy.js"
         - "12.cy.js"
         - "13.cy.js"
         - "14.cy.js"
         - "15.cy.js"
         - "16.cy.js"
         - "17.cy.js"
         - "20.cy.js"
         - "21.cy.js"
         - "20.cy.js"
         - "21.cy.js"
         - "22.cy.js"
         - "23.cy.js"
         - "24.cy.js"
         - "25.cy.js"
         - "26.cy.js"
         - "27.cy.js"
         - "28.cy.js"
         - "29.cy.js"
         - "30.cy.js"
         - "31.cy.js"
         - "32.cy.js"
         - "33.cy.js"
         - "34.cy.js"
         - "35.cy.js"
         - "36.cy.js"
         - "37.cy.js"
         - "38.cy.js"
         - "39.cy.js"
         - "40.cy.js"
         - "41.cy.js"
         - "42.cy.js"
         - "43.cy.js"
         - "44.cy.js"
         - "45.cy.js"
         - "46.cy.js"
         - "47.cy.js"
         - "48.cy.js"
         - "49.cy.js"
         - "50.cy.js"
         - "51.cy.js"
         - "52.cy.js"
         - "53.cy.js"
         - "54.cy.js"
         - "55.cy.js"
         - "56.cy.js"
         - "57.cy.js"
         - "58.cy.js"
         - "59.cy.js"
         - "60.cy.js"
         - "61.cy.js"
         - "62.cy.js"
         - "63.cy.js"
         - "64.cy.js"
         - "65.cy.js"
         - "66.cy.js"
         - "67.cy.js"
         - "68.cy.js"
         - "69.cy.js"
         - "70.cy.js"
         - "71.cy.js"
         - "72.cy.js"
         - "73.cy.js"
         - "74.cy.js"
         - "75.cy.js"
         - "76.cy.js"
         - "77.cy.js"
         - "78.cy.js"
         - "79.cy.js"
         - "80.cy.js"
         - "81.cy.js"
         - "82.cy.js"
         - "83.cy.js"
         - "84.cy.js"
         - "85.cy.js"
         - "86.cy.js"
         - "87.cy.js"
         - "88.cy.js"
         - "89.cy.js"
         - "90.cy.js"
         - "91.cy.js"
         - "92.cy.js"
         - "93.cy.js"
         - "94.cy.js"
         - "95.cy.js"
         - "96.cy.js"
         - "97.cy.js"
         - "98.cy.js"
         - "99.cy.js"
         - "100.cy.js"


    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress run --spec "cypress/e2e/${{ matrix.spec_file }}" --config video=false --record --key fede15fc-970a-4cb4-a077-518573466e27

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
            cypress/fixtures/missing_elements2603.json
              cypress/fixtures/missing_elements2604.json
              cypress/fixtures/missing_elements2605.json
              cypress/fixtures/missing_elements2606.json
              cypress/fixtures/missing_elements2607.json
              cypress/fixtures/missing_elements2608.json
              cypress/fixtures/missing_elements2609.json
              cypress/fixtures/missing_elements2610.json
              cypress/fixtures/missing_elements2611.json
              cypress/fixtures/missing_elements2612.json
              cypress/fixtures/missing_elements2613.json
              cypress/fixtures/missing_elements2614.json
              cypress/fixtures/missing_elements2615.json
              cypress/fixtures/missing_elements2616.json
              cypress/fixtures/missing_elements2617.json
              cypress/fixtures/missing_elements2618.json
              cypress/fixtures/missing_elements2619.json
              cypress/fixtures/missing_elements2620.json
              cypress/fixtures/missing_elements2621.json
              cypress/fixtures/missing_elements2622.json
              cypress/fixtures/missing_elements2623.json
              cypress/fixtures/missing_elements2624.json
              cypress/fixtures/missing_elements2625.json
              cypress/fixtures/missing_elements2626.json
              cypress/fixtures/missing_elements2627.json
              cypress/fixtures/missing_elements2628.json
              cypress/fixtures/missing_elements2629.json
              cypress/fixtures/missing_elements2630.json
              cypress/fixtures/missing_elements2631.json
              cypress/fixtures/missing_elements2632.json
              cypress/fixtures/missing_elements2633.json
              cypress/fixtures/missing_elements2634.json
              cypress/fixtures/missing_elements2635.json
              cypress/fixtures/missing_elements2636.json
              cypress/fixtures/missing_elements2637.json
              cypress/fixtures/missing_elements2638.json
              cypress/fixtures/missing_elements2639.json
              cypress/fixtures/missing_elements2640.json
              cypress/fixtures/missing_elements2641.json
              cypress/fixtures/missing_elements2642.json
              cypress/fixtures/missing_elements2643.json
              cypress/fixtures/missing_elements2644.json
              cypress/fixtures/missing_elements2645.json
              cypress/fixtures/missing_elements2646.json
              cypress/fixtures/missing_elements2647.json
              cypress/fixtures/missing_elements2648.json
              cypress/fixtures/missing_elements2649.json
              cypress/fixtures/missing_elements2650.json
              cypress/fixtures/missing_elements2651.json
              cypress/fixtures/missing_elements2652.json
              cypress/fixtures/missing_elements2653.json
              cypress/fixtures/missing_elements2654.json
              cypress/fixtures/missing_elements2655.json
              cypress/fixtures/missing_elements2656.json
              cypress/fixtures/missing_elements2657.json
              cypress/fixtures/missing_elements2658.json
              cypress/fixtures/missing_elements2659.json
              cypress/fixtures/missing_elements2660.json
              cypress/fixtures/missing_elements2661.json
              cypress/fixtures/missing_elements2662.json
              cypress/fixtures/missing_elements2663.json
              cypress/fixtures/missing_elements2664.json
              cypress/fixtures/missing_elements2665.json
              cypress/fixtures/missing_elements2666.json
              cypress/fixtures/missing_elements2667.json
              cypress/fixtures/missing_elements2668.json
              cypress/fixtures/missing_elements2669.json
              cypress/fixtures/missing_elements2670.json
              cypress/fixtures/missing_elements2671.json
              cypress/fixtures/missing_elements2672.json
              cypress/fixtures/missing_elements2673.json
              cypress/fixtures/missing_elements2674.json
              cypress/fixtures/missing_elements2675.json
              cypress/fixtures/missing_elements2676.json
              cypress/fixtures/missing_elements2677.json
              cypress/fixtures/missing_elements2678.json
              cypress/fixtures/missing_elements2679.json
              cypress/fixtures/missing_elements2680.json
              cypress/fixtures/missing_elements2681.json
              cypress/fixtures/missing_elements2682.json
              cypress/fixtures/missing_elements2683.json
              cypress/fixtures/missing_elements2684.json
              cypress/fixtures/missing_elements2685.json
              cypress/fixtures/missing_elements2686.json
              cypress/fixtures/missing_elements2687.json
              cypress/fixtures/missing_elements2688.json
              cypress/fixtures/missing_elements2689.json
              cypress/fixtures/missing_elements2690.json
              cypress/fixtures/missing_elements2691.json
              cypress/fixtures/missing_elements2692.json
              cypress/fixtures/missing_elements2693.json
              cypress/fixtures/missing_elements2694.json
              cypress/fixtures/missing_elements2695.json
              cypress/fixtures/missing_elements2696.json
              cypress/fixtures/missing_elements2697.json
              cypress/fixtures/missing_elements2698.json
              cypress/fixtures/missing_elements2699.json
              cypress/fixtures/missing_elements2700.json
              cypress/fixtures/missing_elements2701.json
              cypress/fixtures/missing_elements2702.json
              cypress/fixtures/missing_elements2703.json
              cypress/fixtures/missing_elements2704.json
              cypress/fixtures/missing_elements2705.json
              cypress/fixtures/missing_elements2706.json
              cypress/fixtures/missing_elements2707.json
              cypress/fixtures/missing_elements2708.json
              cypress/fixtures/missing_elements2709.json
              cypress/fixtures/missing_elements2710.json
              cypress/fixtures/missing_elements2711.json
              cypress/fixtures/missing_elements2712.json
              cypress/fixtures/missing_elements2713.json
              cypress/fixtures/missing_elements2714.json
              cypress/fixtures/missing_elements2715.json
              cypress/fixtures/missing_elements2716.json
              cypress/fixtures/missing_elements2717.json
              cypress/fixtures/missing_elements2718.json
              cypress/fixtures/missing_elements2719.json
              cypress/fixtures/missing_elements2720.json
              cypress/fixtures/missing_elements2721.json
              cypress/fixtures/missing_elements2722.json
              cypress/fixtures/missing_elements2723.json
              cypress/fixtures/missing_elements2724.json
              cypress/fixtures/missing_elements2725.json
              cypress/fixtures/missing_elements2726.json
              cypress/fixtures/missing_elements2727.json
              cypress/fixtures/missing_elements2728.json
              cypress/fixtures/missing_elements2729.json
              cypress/fixtures/missing_elements2730.json
              cypress/fixtures/missing_elements2731.json
              cypress/fixtures/missing_elements2732.json
              cypress/fixtures/missing_elements2733.json
              cypress/fixtures/missing_elements2734.json
              cypress/fixtures/missing_elements2735.json
              cypress/fixtures/missing_elements2736.json
              cypress/fixtures/missing_elements2737.json
              cypress/fixtures/missing_elements2738.json
              cypress/fixtures/missing_elements2739.json
              cypress/fixtures/missing_elements2740.json
              cypress/fixtures/missing_elements2741.json
              cypress/fixtures/missing_elements2742.json
              cypress/fixtures/missing_elements2743.json
              cypress/fixtures/missing_elements2744.json
              cypress/fixtures/missing_elements2745.json
              cypress/fixtures/missing_elements2746.json
              cypress/fixtures/missing_elements2747.json
              cypress/fixtures/missing_elements2748.json
              cypress/fixtures/missing_elements2749.json
              cypress/fixtures/missing_elements2750.json
              cypress/fixtures/missing_elements2751.json
              cypress/fixtures/missing_elements2752.json
              cypress/fixtures/missing_elements2753.json
              cypress/fixtures/missing_elements2754.json
              cypress/fixtures/missing_elements2755.json
              cypress/fixtures/missing_elements2756.json
              cypress/fixtures/missing_elements2757.json
              cypress/fixtures/missing_elements2758.json
              cypress/fixtures/missing_elements2759.json
              cypress/fixtures/missing_elements2760.json
              cypress/fixtures/missing_elements2761.json
              cypress/fixtures/missing_elements2762.json
              cypress/fixtures/missing_elements2763.json
              cypress/fixtures/missing_elements2764.json
              cypress/fixtures/missing_elements2765.json
              cypress/fixtures/missing_elements2766.json
              cypress/fixtures/missing_elements2767.json
              cypress/fixtures/missing_elements2768.json
              cypress/fixtures/missing_elements2769.json
              cypress/fixtures/missing_elements2770.json
              cypress/fixtures/missing_elements2771.json
              cypress/fixtures/missing_elements2772.json
              cypress/fixtures/missing_elements2773.json
              cypress/fixtures/missing_elements2774.json
              cypress/fixtures/missing_elements2775.json
              cypress/fixtures/missing_elements2776.json
              cypress/fixtures/missing_elements2777.json
              cypress/fixtures/missing_elements2778.json
              cypress/fixtures/missing_elements2779.json
              cypress/fixtures/missing_elements2780.json
              cypress/fixtures/missing_elements2781.json
              cypress/fixtures/missing_elements2782.json
              cypress/fixtures/missing_elements2783.json
              cypress/fixtures/missing_elements2784.json
              cypress/fixtures/missing_elements2785.json
              cypress/fixtures/missing_elements2786.json
              cypress/fixtures/missing_elements2787.json
              cypress/fixtures/missing_elements2788.json
              cypress/fixtures/missing_elements2789.json
              cypress/fixtures/missing_elements2790.json
              cypress/fixtures/missing_elements2791.json
              cypress/fixtures/missing_elements2792.json
              cypress/fixtures/missing_elements2793.json
              cypress/fixtures/missing_elements2794.json
              cypress/fixtures/missing_elements2795.json
              cypress/fixtures/missing_elements2796.json
              cypress/fixtures/missing_elements2797.json
              cypress/fixtures/missing_elements2798.json
              cypress/fixtures/missing_elements2799.json
              cypress/fixtures/missing_elements2800.json
              cypress/fixtures/missing_elements2801.json
              cypress/fixtures/missing_elements2802.json
              cypress/fixtures/missing_elements2803.json
