on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spec_file:
         - "01.cy.js"
         - "02.cy.js"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm install
          # Add any additional setup steps here, if needed

      - name: Run Cypress tests
        run: |
          npx cypress install # This ensures Cypress is installed and up-to-date
          # Wrap the Cypress run command in a try-catch block
          set +e
          npx cypress run --spec "cypress/e2e/${{ matrix.spec_file }}" --config video=false --record --key fede15fc-970a-4cb4-a077-518573466e27
          # Store the exit code in a variable
          EXIT_CODE=$?
          # Set back to normal behavior (exit on error)
          set -e
          # Check if the exit code is non-zero (indicating failure)
          if [ $EXIT_CODE -ne 0 ]; then
            echo "Some tests failed but continuing..."
          fi

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Last Run
          path: |
            cypress/videos
            cypress/screenshots
            cypress/fixtures/missing_elements3151.json
            cypress/fixtures/missing_elements3152.json
            cypress/fixtures/missing_elements3153.json
            cypress/fixtures/missing_elements3154.json